package data.scripts.world
package systems

import com.fs.starfarer.api.Global
import com.fs.starfarer.api.campaign.SectorAPI
import com.fs.starfarer.api.impl.campaign.ids.Terrain
import com.fs.starfarer.api.impl.campaign.terrain.AsteroidFieldTerrainPlugin.AsteroidFieldParams
import com.fs.starfarer.api.impl.campaign.ids.Conditions._
import com.fs.starfarer.api.impl.campaign.ids.Submarkets._

import java.awt.Color

/**
  * Created by hawk on 7/12/16.
  */
object Rousseau {

  def generate(sector: SectorAPI): Unit = {
    val system = sector createStarSystem "Rousseau"
    val hyper = Global.getSector.getHyperspace

    // create the star and generate the hyperspace anchor for this system
    val star = system.initStar("rousseau", // unique id for this star
                               "star_white", // id in planets.json
                                 840f,		// radius (in pixels at default zoom)
                                 1100, // corona radius, from star edge
                                 5f, // solar wind burn level
                                 0.6f, // flare probability
                                 2f); // cr loss mult

    // Rousseau's Trojans --------------------------------------------------
    val trojansL4 = system.addTerrain(Terrain.ASTEROID_FIELD,
                                      new AsteroidFieldParams(
                                        400f, // min radius
                                        600f, // max radius
                                        16, // min asteroid count
                                        24, // max asteroid count
                                        4f, // min asteroid radius
                                        16f, // max asteroid radius
                                        "Rousseau L4 Trojans"));
    // null for default name
    val trojansL5 = system.addTerrain(Terrain.ASTEROID_FIELD,
                                      new AsteroidFieldParams(
                                        400f, // min radius
                                        600f, // max radius
                                        16, // min asteroid count
                                        24, // max asteroid count
                                        4f, // min asteroid radius
                                        16f, // max asteroid radius
                                        "Rousseau L5 Asteroids"))
    trojansL4.setCircularOrbit(star, 230 + 60, 9500, 450)
    trojansL5.setCircularOrbit(star, 230 - 60, 9500, 450)

    system.addAsteroidBelt(star, 150, 3100, 128, 60, 80, Terrain
      .ASTEROID_BELT, "The Inner Belt")

    val sophie = system.addPlanet("planet_sophie", star, "Sophie",
                                "irradiated", 60, 100, 3500, 200)
    /*
		 * addPlanet() parameters:
		 * 1. Unique id for this planet (or null to have it be autogenerated)
		 * 2. What the planet orbits (orbit is always circular)
		 * 3. Name
		 * 4. Planet type id in planets.json
		 * 5. Starting angle in orbit, i.e. 0 = to the right of the star
		 * 6. Planet radius, pixels at default zoom
		 * 7. Orbit radius, pixels at default zoom
		 * 8. Days it takes to complete an orbit. 1 day = 10 seconds.
		 */
    // the Brumaire system ---------------------------------------------------
    val brumaire = system.addPlanet("planet_brumaire",
                                    star,
                                    "Brumaire",
                                    "gas_giant",
                                    0,
                                    400, // planet radius
                                    6500, // orbital radius
                                    350 // orbital period
                                     )

    brumaire.getSpec().setPlanetColor(new Color(200,245,255,255))
    brumaire.getSpec().setAtmosphereColor(new Color(220,240,250,150))
    brumaire.getSpec().setCloudColor(new Color(220,240,250,200))
    brumaire.getSpec().setGlowTexture(Global.getSettings.getSpriteName
    ("hab_glows", "banded"))
    brumaire.getSpec().setGlowColor(new Color(0,205,255,62))
    brumaire.getSpec().setUseReverseLightForGlow(true)
    brumaire.getSpec().setIconColor(new Color(250,205,225,255))

    brumaire.applySpecChanges()
    // brumaire's rings
    system.addRingBand(brumaire, "misc", "rings1", 256f, 2, Color.white, 256f,
                       875, 33f, Terrain.RING, null)
    system.addRingBand(brumaire, "misc", "rings1", 256f, 3, Color.white, 256f,
                       1050, 33f, Terrain.RING, null)
    // Brumaire's two smaller moons
    val fraternite = system.addPlanet("moon_fraternite",
                                      brumaire, "Fraternité",
                                      "rocky_metallic", 30, 85, 1650, 50)
    val egalite = system.addPlanet("moon_egalite",
                                      brumaire, "Égalité",
                                      "rocky_ice", 45, 45, 1870, 65)


    // Liberte & its' station -------------------------------------------------
    val liberte = system.addPlanet("planet_liberte",
                                   brumaire,
                                   "Liberté",
                                  "terran-eccentric",
                                   0,
                                   135f,
                                   1460f,
                                   42f)

    // add Liberte city lights
    liberte.getSpec.setGlowTexture(
      Global.getSettings.getSpriteName("hab_glows", "sindria"))
    liberte.getSpec.setGlowColor(new Color(255,255,255,255))
    liberte.getSpec.setUseReverseLightForGlow(true)
    liberte.applySpecChanges()

    liberte.setInteractionImage("illustrations", "city_from_above")

    val liberteStation = system.addCustomEntity("station_liberte",
                                                "Al Qasbah Orbital",
                                                "station_side03",
                                                "directory")
    liberteStation.setCircularOrbitPointingDown(
      liberte,
      45,
      300,
      50)
    liberteStation.setInteractionImage("illustrations", "terran_orbit")
    liberteStation.setCustomDescriptionId("station_liberte")

    liberte addMarket ( "directory", "Liberté", 7, 0.3f
                      , Seq( URBANIZED_POLITY, REGIONAL_CAPITAL
                           , ORBITAL_STATION, MILITARY_BASE
                           , HEADQUARTERS, ORGANICS_COMPLEX
                           , TERRAN, POPULATION_7)
                      , Seq( GENERIC_MILITARY, SUBMARKET_BLACK, SUBMARKET_OPEN)
                      , connectedEntities = liberteStation)

    val jumpPoint = Global.getFactory.createJumpPoint("liberte_jump_point",
                                                       "Liberté Crossing")

    val orbit = Global.getFactory.createCircularOrbit(brumaire, 0, 500, 30)
    jumpPoint.setOrbit(orbit)
    jumpPoint.setRelatedPlanet(liberte)
    jumpPoint.setStandardWormholeToHyperspaceVisual()
    jumpPoint.setCircularOrbit( star, 60, 3000, 100)
    system.addEntity(jumpPoint)

    system.addRingBand(brumaire, "misc", "rings1", 256f, 3, Color.white, 256f,
                       700,
                       220f, null, null)
    system.addRingBand(brumaire, "misc", "rings2", 256f, 2, Color.white, 256f,
                       800, 226f, null, null)

    system.autogenerateHyperspaceJumpPoints(true, true)
  }

}
